###
POST https://{{host}}/api/employee/list
Accept: application/json
Content-Type: application/json

{"data": {"locale": "ru_RU"}}


###
POST https://{{host}}/api/employee/workTime/generate
Accept: application/json
Content-Type: application/json

{"data": {}}

### Boo
POST https://{{host}}/api/employee/workTime/list
Accept: application/json
Content-Type: application/json

{
  "data": {
    "employeeRef": 2,
    "dateBegin": "2021-01-01T00:00:00Z",
    "dateEnd": "2021-12-31T23:59:59Z"
  }
}


###

