###
POST https://{{host}}/api/employee/list
Accept: application/json
Content-Type: application/json

{"data": {"locale": "ru_RU"}}

###
POST https://{{host}}/api/employee/profile/save
Accept: application/json
Content-Type: application/json

{
  "data": {
    "user": {
      "id": 1,
      "name": "Alex Test",
      "emails": ["alex1@flancer64.com"],
      "phones": ["29171703"]
    }
  }
}


###
POST https://{{host}}/api/employee/workTime/generate
Accept: application/json
Content-Type: application/json

{"data": {}}

###
POST https://{{host}}/api/employee/workTime/list
Accept: application/json
Content-Type: application/json

{
  "data": {
    "employeeRef": 2,
    "dateBegin": "2021-01-01T00:00:00Z",
    "dateEnd": "2021-12-31T23:59:59Z"
  }
}

###
POST https://{{host}}/api/employee/workTime/save
Accept: application/json
Content-Type: application/json

{
  "data": {
    "item": {
      "employeeRef": 2,
      "start": "2021-01-13T07:00:00.000Z",
      "duration": 660
    }
  }
}


###

