###
POST https://{{host}}/api/user/changePassword
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{sessionId}}

{"data": {"passwordCurrent": "other", "passwordNew": "test"}}

###
